# Generated by Django 4.0.3 on 2022-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0025_rename_ritfacultybio_faculty_facultybio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketry',
            name='position',
            field=models.CharField(choices=[('None', 'None'), ('Head', 'Head'), ('SSH', 'Subsystem Head'), ('CSE', 'Chief System Engineer'), ('SE', 'System Engineer'), ('SSE', 'Subsystem Engineer')], max_length=5),
        ),
        migrations.AlterField(
            model_name='technical',
            name='position',
            field=models.CharField(choices=[('None', 'None'), ('Head', 'Head'), ('SSH', 'Subsystem Head'), ('CSE', 'Chief System Engineer'), ('SE', 'System Engineer'), ('SSE', 'Subsystem Engineer')], max_length=5),
        ),
    ]
